2015-09-09 08:43:56,713 [18] ERROR Zero.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2015-09-09 08:45:53,603 [8] ERROR Zero.DataAccess.DbHelper - 参数化查询 '(@CompanyId nvarchar(4000))SELECT top 1 CompanyId,ParentId,Categ' 需要参数 '@CompanyId'，但未提供该参数。
2015-09-09 14:31:36,231 [28] ERROR Zero.DataAccess.DbHelper - 在此上下文中不允许使用名称 "匿名"。有效表达式包括常量、常量表达式和变量(在某些上下文中)。不允许使用列名。
2015-09-09 14:35:37,774 [36] ERROR Zero.DataAccess.DbHelper - 无法对 表 'Base_Article' 执行 删除，因为它不存在，或者您没有所需的权限。
